package com.qiyun.mapper2;

import com.qiyun.model2.MemberScore2;
import java.util.List;

public interface MemberScoreMapper2 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_score
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_score
     *
     * @mbg.generated
     */
    int insert(MemberScore2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_score
     *
     * @mbg.generated
     */
    MemberScore2 selectByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_score
     *
     * @mbg.generated
     */
    List<MemberScore2> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberScore2 record);
}