package com.qiyun.dto;

import java.util.Date;


/**
 * AbstractMemberOperTrack generated by MyEclipse Persistence Tools
 */

public  class MemberOperTrack implements java.io.Serializable {

	// Fields
	private  Integer OPER_LINE_NO;
	// 操作流水编号
	private Integer operLineNo;
	// 设备id
	private String terminalId;
	// 会员帐号
	private String account;
	//平台
	private int platform;
	//版本
	private String version;	
	// 操作类型
	private int operType;
	// ip地址
	private String ip;
	// ip所解析的地区
	private String fromCountry;
	private String fromArea;
	// 生成时间
	private Date createDateTime;
	//请求方法
	private String url;
	//请求路径


	public Integer getOPER_LINE_NO() {
		return OPER_LINE_NO;
	}

	public void setOPER_LINE_NO(Integer OPER_LINE_NO) {
		this.OPER_LINE_NO = OPER_LINE_NO;
	}

	public String getReferer() {
		return referer;
	}

	public void setReferer(String referer) {
		this.referer = referer;
	}

	private String referer;

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}



	public MemberOperTrack() {

	}


	public Integer getOperLineNo() {
		return operLineNo;
	}

	public void setOperLineNo(Integer operLineNo) {
		this.operLineNo = operLineNo;
	}

	public String getTerminalId() {
		return terminalId;
	}

	public void setTerminalId(String terminalId) {
		this.terminalId = terminalId;
	}

	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public int getPlatform() {
		return platform;
	}

	public void setPlatform(int platform) {
		this.platform = platform;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public int getOperType() {
		return operType;
	}

	public void setOperType(int operType) {
		this.operType = operType;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getFromCountry() {
		return fromCountry;
	}

	public void setFromCountry(String fromCountry) {
		this.fromCountry = fromCountry;
	}

	public String getFromArea() {
		return fromArea;
	}

	public void setFromArea(String fromArea) {
		this.fromArea = fromArea;
	}

	public Date getCreateDateTime() {
		return createDateTime;
	}

	public void setCreateDateTime(Date createDateTime) {
		this.createDateTime = createDateTime;
	}
	/** default constructor */

}