package com.qiyun.model;

// Generated by MyEclipse Persistence Tools

import com.qiyun.grabber.model.AbstractMatchBase;

import java.util.Date;

/**
 * FootballMatch generated by MyEclipse Persistence Tools
 */
public class BasketBallBase extends AbstractMatchBase implements java.io.Serializable {

	// Constructors
	private String shortMatchName;
	
	/** 第一节比分* */
	private String firstSection;
	/** 第二节比分* */
	private String secondSection;
	/** 第三节比分* */
	private String thirdSection;
	/** 第四节比分* */
	private String fourthSection;
	/** 加时比分* */
	private String addSection;

	private Integer intTime;
	
	private Integer lineId;
	
	private String mapKey;//用这个关联对阵表
	

	/** default constructor */
	public BasketBallBase() {
	}

	/** full constructor */
	public BasketBallBase(Integer id, String home, Integer homeId, String guest, Integer guestId, Date matchTime, String matchDateStr,
			String bfWhole, String analysisId, String oddId, Integer gameId, String homePm, String guestPm, Integer finalHomeScore,
			Integer finalGuestScore) {
		super(id, home, homeId, guest, guestId, matchTime, matchDateStr, bfWhole, analysisId, oddId, gameId, homePm, guestPm, finalHomeScore,
				finalGuestScore);
	}

	public String getShortMatchName() {
		shortMatchName = shortMatchName == null ? getMatchName() : shortMatchName;
		return shortMatchName;
	}

	public void setShortMatchName(String shortMatchName) {
		this.shortMatchName = shortMatchName;
	}
	
	public String getMapKey(){
		return getIntTime()+"_"+getLineId();
	}

	public String getFirstSection() {
		return firstSection;
	}

	public void setFirstSection(String firstSection) {
		this.firstSection = firstSection;
	}

	public String getSecondSection() {
		return secondSection;
	}

	public void setSecondSection(String secondSection) {
		this.secondSection = secondSection;
	}

	public String getThirdSection() {
		return thirdSection;
	}

	public void setThirdSection(String thirdSection) {
		this.thirdSection = thirdSection;
	}

	public String getFourthSection() {
		return fourthSection;
	}

	public void setFourthSection(String fourthSection) {
		this.fourthSection = fourthSection;
	}

	public String getAddSection() {
		return addSection;
	}

	public void setAddSection(String addSection) {
		this.addSection = addSection;
	}

	public Integer getIntTime() {
		return intTime;
	}

	public void setIntTime(Integer intTime) {
		this.intTime = intTime;
	}

	public Integer getLineId() {
		return lineId;
	}

	public void setLineId(Integer lineId) {
		this.lineId = lineId;
	}

}
