package com.qiyun.model;

// Generated by MyEclipse Persistence Tools

import com.qiyun.grabber.model.AbstractMatchBase;

import java.util.Date;

/**
 * FootballMatch generated by MyEclipse Persistence Tools
 */
public class FootballMatch extends AbstractMatchBase implements java.io.Serializable {

	// Constructors
	private String shortMatchName; 
	
	private String bfHalf; //半全场
	
	private String bfLevel;  //级别
	
	private String outAnalysisId;//外连分析ID OUT_ANALYSIS_ID
	
	private Integer resultOfMatch;
	
	private Integer xyyHomeId;
	
	private Integer xyyGuestId;

	/** default constructor */
	public FootballMatch() {
	}

	/** full constructor */ 
	public FootballMatch(Integer id, String home, Integer homeId, String guest, Integer guestId, Date matchTime, String matchDateStr,
			String bfWhole, String analysisId, String oddId, Integer gameId, String homePm, String guestPm, Integer finalHomeScore,
			Integer finalGuestScore) {
		super(id, home, homeId, guest, guestId, matchTime, matchDateStr, bfWhole, analysisId, oddId, gameId, homePm, guestPm, finalHomeScore, finalGuestScore);
	}
	public String getHomePmShow(){
		String pm=getHomePm();
		if(pm!=null){
			return "["+pm+"]";
		}
		return null;
	}
	public String getGuestPmShow(){
		String pm=getGuestPm();
		if(pm!=null){
			return "["+pm+"]";
		}
		return null;
	}

	public String getShortMatchName() {
		shortMatchName=shortMatchName==null?getMatchName():shortMatchName;
		return shortMatchName;
	}

	public void setShortMatchName(String shortMatchName) {
		this.shortMatchName = shortMatchName;
	}

	public String getBfHalf() {
		return bfHalf;
	}

	public void setBfHalf(String bfHalf) {
		this.bfHalf = bfHalf;
	}

	public String getBfLevel() {
		return bfLevel;
	}

	public void setBfLevel(String bfLevel) {
		this.bfLevel = bfLevel;
	}

	public String getOutAnalysisId() {
		return outAnalysisId;
	}

	public void setOutAnalysisId(String outAnalysisId) {
		this.outAnalysisId = outAnalysisId;
	}

	public Integer getResultOfMatch() {
		return resultOfMatch;
	}

	public void setResultOfMatch(Integer resultOfMatch) {
		this.resultOfMatch = resultOfMatch;
	}

	public Integer getXyyHomeId() {
		return xyyHomeId;
	}

	public void setXyyHomeId(Integer xyyHomeId) {
		this.xyyHomeId = xyyHomeId;
	}

	public Integer getXyyGuestId() {
		return xyyGuestId;
	}

	public void setXyyGuestId(Integer xyyGuestId) {
		this.xyyGuestId = xyyGuestId;
	}
}
