package com.qiyun.model;

// Generated by MyEclipse Persistence Tools

import com.qiyun.grabber.model.AbstractFootballTeam;
import lombok.Builder;

/**
 * FootballTeam generated by MyEclipse Persistence Tools
 */
@Builder
public class FootballTeam extends AbstractFootballTeam implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public FootballTeam() {
	}

	/** full constructor */
	public FootballTeam(String dc, String jc, String fb, String dyj) {
		super(dc, jc, fb, dyj);
	}

	public void setAllName(String name) {
		super.setDc(name);
		super.setJc(name);
		super.setFb(name);
		super.setDyj(name);
	}

}
