package com.qiyun.model;

import com.qiyun.grabber.model.AbstractLotteryTypeProps;

import java.util.List;

// Generated by MyEclipse Persistence Tools

/**
 * LotteryTypeProps generated by MyEclipse Persistence Tools
 */
public class LotteryTypeProps extends AbstractLotteryTypeProps implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public LotteryTypeProps() {
	}

	/** full constructor */
	public LotteryTypeProps(Integer lotteryType, Integer countInBatch, Integer maxWaitTime, Integer dsAheadTime, Integer fsAheadTime) {
		super(lotteryType, countInBatch, maxWaitTime, dsAheadTime, fsAheadTime);
	}
	List<LotteryTypeProps> commendList;
	public List<LotteryTypeProps> getCommendList() {
		return commendList;
	}

	public void setCommendList(List<LotteryTypeProps> commendList) {
		this.commendList = commendList;
	}

}
