package com.qiyun.model2;

public class MemberScore2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_score.MEMBER_ID
     *
     * @mbg.generated
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_score.ACCOUNT
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_score.ABLE_SCORE
     *
     * @mbg.generated
     */
    private Integer ableScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_score.HEAP_SCORE
     *
     * @mbg.generated
     */
    private Integer heapScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_score.MEMBER_ID
     *
     * @return the value of member_score.MEMBER_ID
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_score.MEMBER_ID
     *
     * @param memberId the value for member_score.MEMBER_ID
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_score.ACCOUNT
     *
     * @return the value of member_score.ACCOUNT
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_score.ACCOUNT
     *
     * @param account the value for member_score.ACCOUNT
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_score.ABLE_SCORE
     *
     * @return the value of member_score.ABLE_SCORE
     *
     * @mbg.generated
     */
    public Integer getAbleScore() {
        return ableScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_score.ABLE_SCORE
     *
     * @param ableScore the value for member_score.ABLE_SCORE
     *
     * @mbg.generated
     */
    public void setAbleScore(Integer ableScore) {
        this.ableScore = ableScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_score.HEAP_SCORE
     *
     * @return the value of member_score.HEAP_SCORE
     *
     * @mbg.generated
     */
    public Integer getHeapScore() {
        return heapScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_score.HEAP_SCORE
     *
     * @param heapScore the value for member_score.HEAP_SCORE
     *
     * @mbg.generated
     */
    public void setHeapScore(Integer heapScore) {
        this.heapScore = heapScore;
    }
}