package com.qiyun.ticket;

import com.qiyun.commonModel.LotteryType;
import com.qiyun.commonModel.PlayType;
import com.qiyun.model.TicketStatus;
import com.qiyun.model.WinStatus;
import org.apache.log4j.spi.ErrorCode;

import java.util.Date;

/**
 * AbstractTicket generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTicket implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer planNo;
	private String content;
	private String term;
	private LotteryType lotteryType;
	private Integer amount;
	private Date createDateTime;
	private Date sendDateTime;
	private Date printDateTime;
	private Date dealDateTime;
	private Integer multiple;
	private PlayType playType;
	private Integer isBingo;
	private Double bingoAmount;
	private String bingoContent;
	private TicketStatus status;
	private String addAttribute;
	private String account;
	private String outId;
	private Integer noInBatch;
	private String batchNo;
	private Integer isConvert;
	private Date convertDateTime;
	private String serialNo;
	private TicketProvider provider;
	// 中奖状态
	private WinStatus winStatus;
	private Date openResultTime;
	private Date returnPrizeTime;
	
	/**
	 * 送票、查票错误码
	 */
	private ErrorCode errorCode;

	// Constructors

	public TicketProvider getProvider() {
		return provider;
	}

	public void setProvider(TicketProvider provider) {
		this.provider = provider;
	}

	public String getSerialNo() {
		return serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	/** default constructor */
	public AbstractTicket() {
	}

	/** minimal constructor */
	public AbstractTicket(Integer planNo, String term, Date createDateTime, Date dealDateTime, Integer multiple, PlayType playType,
			TicketStatus status, String account) {
		this.planNo = planNo;
		this.term = term;
		this.createDateTime = createDateTime;
		this.dealDateTime = dealDateTime;
		this.multiple = multiple;
		this.playType = playType;
		this.status = status;
		this.account = account;
	}

	/** full constructor */
	public AbstractTicket(Integer planNo, String content, String term, LotteryType lotteryType, Integer amount, Date createDateTime,
			Date sendDateTime, Date printDateTime, Date dealDateTime, Integer multiple, PlayType playType, Integer isBingo, Double bingoAmount,
			String bingoContent, TicketStatus status, String addAttribute, String account, String outId, Integer noInBatch, String batchNo,
			Integer isConvert, Date convertDateTime) {
		this.planNo = planNo;
		this.content = content;
		this.term = term;
		this.lotteryType = lotteryType;
		this.amount = amount;
		this.createDateTime = createDateTime;
		this.sendDateTime = sendDateTime;
		this.printDateTime = printDateTime;
		this.dealDateTime = dealDateTime;
		this.multiple = multiple;
		this.playType = playType;
		this.isBingo = isBingo;
		this.bingoAmount = bingoAmount;
		this.bingoContent = bingoContent;
		this.status = status;
		this.addAttribute = addAttribute;
		this.account = account;
		this.outId = outId;
		this.noInBatch = noInBatch;
		this.batchNo = batchNo;
		this.isConvert = isConvert;
		this.convertDateTime = convertDateTime;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPlanNo() {
		return this.planNo;
	}

	public void setPlanNo(Integer planNo) {
		this.planNo = planNo;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getTerm() {
		return this.term;
	}

	public void setTerm(String term) {
		this.term = term;
	}

	public LotteryType getLotteryType() {
		return this.lotteryType;
	}
	

	public void setLotteryType(LotteryType lotteryType) {
		this.lotteryType = lotteryType;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public Date getCreateDateTime() {
		return this.createDateTime;
	}

	public void setCreateDateTime(Date createDateTime) {
		this.createDateTime = createDateTime;
	}

	public Date getSendDateTime() {
		return this.sendDateTime;
	}

	public void setSendDateTime(Date sendDateTime) {
		this.sendDateTime = sendDateTime;
	}

	public Date getPrintDateTime() {
		return this.printDateTime;
	}

	public void setPrintDateTime(Date printDateTime) {
		this.printDateTime = printDateTime;
	}

	public Date getDealDateTime() {
		return this.dealDateTime;
	}

	public void setDealDateTime(Date dealDateTime) {
		this.dealDateTime = dealDateTime;
	}

	public Integer getMultiple() {
		return this.multiple;
	}

	public void setMultiple(Integer multiple) {
		this.multiple = multiple;
	}

	public PlayType getPlayType() {
		return this.playType;
	}

	public void setPlayType(PlayType playType) {
		this.playType = playType;
	}

	public Integer getIsBingo() {
		return this.isBingo;
	}

	public void setIsBingo(Integer isBingo) {
		this.isBingo = isBingo;
	}

	public Double getBingoAmount() {
		return this.bingoAmount;
	}

	public void setBingoAmount(Double bingoAmount) {
		this.bingoAmount = bingoAmount;
	}

	public String getBingoContent() {
		return this.bingoContent;
	}

	public void setBingoContent(String bingoContent) {
		this.bingoContent = bingoContent;
	}

	public TicketStatus getStatus() {
		return this.status;
	}

	public void setStatus(TicketStatus status) {
		this.status = status;
	}

	public String getAddAttribute() {
		return this.addAttribute;
	}

	public void setAddAttribute(String addAttribute) {
		this.addAttribute = addAttribute;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getOutId() {
		return this.outId;
	}

	public void setOutId(String outId) {
		this.outId = outId;
	}

	public Integer getNoInBatch() {
		return this.noInBatch;
	}

	public void setNoInBatch(Integer noInBatch) {
		this.noInBatch = noInBatch;
	}

	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	public Integer getIsConvert() {
		return this.isConvert;
	}

	public void setIsConvert(Integer isConvert) {
		this.isConvert = isConvert;
	}

	public Date getConvertDateTime() {
		return this.convertDateTime;
	}

	public void setConvertDateTime(Date convertDateTime) {
		this.convertDateTime = convertDateTime;
	}

	public ErrorCode getErrorCode() {
		return errorCode;
	}

	public void setErrorCode(ErrorCode errorCode) {
		this.errorCode = errorCode;
	}

	public WinStatus getWinStatus() {
		if(winStatus==null ){
			if(bingoAmount!=null && bingoAmount >0){
				winStatus=WinStatus.AWARD;
			}else{
				winStatus=WinStatus.NOT_RESULT;
			}
		}
		return winStatus;
	}

	public void setWinStatus(WinStatus winStatus) {
		this.winStatus = winStatus;
	}

	public Date getOpenResultTime() {
		return openResultTime;
	}

	public void setOpenResultTime(Date openResultTime) {
		this.openResultTime = openResultTime;
	}

	public Date getReturnPrizeTime() {
		return returnPrizeTime;
	}

	public void setReturnPrizeTime(Date returnPrizeTime) {
		this.returnPrizeTime = returnPrizeTime;
	}
}