package com.qiyun.grabber.football;

import java.util.Date;

/**
 * AbstractFootballOp generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public abstract class AbstractFootballOp implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer matchId;

	private Double home;

	private Integer homeChange;

	private Double draw;

	private Integer drawChange;

	private Double guest;

	private Integer guestChange;

	private Double kellyHome;

	private Integer kellyHomeChange;

	private Double kellyDraw;

	private Integer kellyDrawChange;

	private Double kellyGuest;

	private Integer kellyGuestChange;

	private Integer isFirst;

	private Date time;
	
	private String company;

	// Constructors

	/** default constructor */
	public AbstractFootballOp() {
	}

	/** minimal constructor */
	public AbstractFootballOp(Integer matchId) {
		this.matchId = matchId;
	}

	// Property accessors

	public AbstractFootballOp(Integer id, Integer matchId, Double home, Integer homeChange, Double draw, Integer drawChange, Double guest,
			Integer guestChange, Double kellyHome, Integer kellyHomeChange, Double kellyDraw, Integer kellyDrawChange, Double kellyGuest,
			Integer kellyGuestChange, Integer isFirst, Date time) {
		super();
		this.id = id;
		this.matchId = matchId;
		this.home = home;
		this.homeChange = homeChange;
		this.draw = draw;
		this.drawChange = drawChange;
		this.guest = guest;
		this.guestChange = guestChange;
		this.kellyHome = kellyHome;
		this.kellyHomeChange = kellyHomeChange;
		this.kellyDraw = kellyDraw;
		this.kellyDrawChange = kellyDrawChange;
		this.kellyGuest = kellyGuest;
		this.kellyGuestChange = kellyGuestChange;
		this.isFirst = isFirst;
		this.time = time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getMatchId() {
		return this.matchId;
	}

	public void setMatchId(Integer matchId) {
		this.matchId = matchId;
	}

	public Double getHome() {
		return this.home;
	}

	public void setHome(Double home) {
		this.home = home;
	}

	public Integer getHomeChange() {
		return this.homeChange;
	}

	public void setHomeChange(Integer homeChange) {
		this.homeChange = homeChange;
	}

	public Double getDraw() {
		return this.draw;
	}

	public void setDraw(Double draw) {
		this.draw = draw;
	}

	public Integer getDrawChange() {
		return this.drawChange;
	}

	public void setDrawChange(Integer drawChange) {
		this.drawChange = drawChange;
	}

	public Double getGuest() {
		return this.guest;
	}

	public void setGuest(Double guest) {
		this.guest = guest;
	}

	public Integer getGuestChange() {
		return this.guestChange;
	}

	public void setGuestChange(Integer guestChange) {
		this.guestChange = guestChange;
	}

	public Integer getIsFirst() {
		return this.isFirst;
	}

	public void setIsFirst(Integer isFirst) {
		this.isFirst = isFirst;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Double getKellyHome() {
		return kellyHome;
	}

	public void setKellyHome(Double kellyHome) {
		this.kellyHome = kellyHome;
	}

	public Integer getKellyHomeChange() {
		return kellyHomeChange;
	}

	public void setKellyHomeChange(Integer kellyHomeChange) {
		this.kellyHomeChange = kellyHomeChange;
	}

	public Double getKellyDraw() {
		return kellyDraw;
	}

	public void setKellyDraw(Double kellyDraw) {
		this.kellyDraw = kellyDraw;
	}

	public Integer getKellyDrawChange() {
		return kellyDrawChange;
	}

	public void setKellyDrawChange(Integer kellyDrawChange) {
		this.kellyDrawChange = kellyDrawChange;
	}

	public Double getKellyGuest() {
		return kellyGuest;
	}

	public void setKellyGuest(Double kellyGuest) {
		this.kellyGuest = kellyGuest;
	}

	public Integer getKellyGuestChange() {
		return kellyGuestChange;
	}

	public void setKellyGuestChange(Integer kellyGuestChange) {
		this.kellyGuestChange = kellyGuestChange;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

}