package com.qiyun.grabber.football;

// Generated by MyEclipse Persistence Tools


import com.qiyun.util.NumberTools;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * LotteryDcSpfaward generated by MyEclipse Persistence Tools
 */
public class LotteryDcSpfaward extends AbstractLotteryDcSpfaward implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public LotteryDcSpfaward() {
	}

	/** full constructor */
	public LotteryDcSpfaward(Integer matchId, Integer dcId, Double homeWinAward, Double guestWinAward, Double drawAward, Date lastUpdateTime) {
		super(matchId, dcId, homeWinAward, guestWinAward, drawAward, lastUpdateTime);
	}

	public Map<String, String> getJsonMap() {
		Map<String, String> jsonMap = new HashMap<String, String>();
		double[] awards = getAwardArr();
		for (int i = 0; i < awards.length; i++) {
			jsonMap.put("sp_" + getDcId() + "_spf_" + i, awards[i] + "");
		}
		return jsonMap;
	}

	public String getHomebetRate() {
		return NumberTools.doubleToPercent(1 / getHomeWinAward(), "0%");
	}

	public String getGuestbetRate() {
		return NumberTools.doubleToPercent(1 / getGuestWinAward(), "0%");
	}

	public String getDrawbetRate() {
		return NumberTools.doubleToPercent(1 / getDrawAward(), "0%");
	}
}
