package com.qiyun.grabber.football;

// Generated by MyEclipse Persistence Tools

import com.qiyun.commonModel.LotteryType;

/**
 * SfpArrange generated by MyEclipse Persistence Tools
 */
public class SfpArrange extends AbstractSfpArrange implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SfpArrange() {
	}

	/** minimal constructor */
	public SfpArrange(Integer id, LotteryType lotteryType, String term) {
		super(id, lotteryType, term);
	}

	/** full constructor */
	public SfpArrange(Integer id, LotteryType lotteryType, String term, String homeTeam, String awaryTream, String matchName, String matchDateTime,
			Integer seq) {
		super(id, lotteryType, term, homeTeam, awaryTream, matchName, matchDateTime, seq);
	}

}
