package com.qiyun.grabber;

import com.qiyun.common.CommonStatus;
import com.qiyun.commonModel.LotteryType;
import com.qiyun.model.LotteryTermStatus;

import java.util.Date;


/**
 * AbstractLotteryTerm generated by MyEclipse Persistence Tools
 */

public abstract class AbstractLotteryTerm implements java.io.Serializable {

	// Fields
	// 无逻辑id
	private Integer id;
	// 彩种
	private LotteryType lotteryType;
	// 彩期
	private String term;
	// 外部彩期
	private String outTerm;
	// 开奖时间
	private Date openDateTime;
	// 开始时间
	private Date startDateTime;
	// 结束时间
	private Date endDateTime;
	// 终端截止时间
	private Date terminalEndDateTime;
	// 是否可用
	private CommonStatus isAble;
	// 是否当前期
	private CommonStatus isCurrentTerm;
	// 彩期状态
	private LotteryTermStatus status;
	// 开奖结果
	private String result;
	// 开奖描述 奖级^中奖注数^每注奖金
	private String resultDetail;
	// 奖池
	private String awardPool;
	// 投注额
	private String totalAmount;
	// 试机号
	private String testMachineCode;

	private CommonStatus isBooking;
	// 彩票管家是否可用
	private CommonStatus lotMgrIsAble;

	// Constructors

	/** default constructor */
	public AbstractLotteryTerm() {
	}

	/** minimal constructor */
	public AbstractLotteryTerm(Integer id, LotteryType lotteryType, String term, CommonStatus isAble, CommonStatus isCurrentTerm,
                               LotteryTermStatus status) {
		this.id = id;
		this.lotteryType = lotteryType;
		this.term = term;
		this.isAble = isAble;
		this.isCurrentTerm = isCurrentTerm;
		this.status = status;
	}

	/** full constructor */
	public AbstractLotteryTerm(Integer id, LotteryType lotteryType, String term, Date openDateTime, Date startDateTime, Date endDateTime,
                               Date terminalEndDateTime, CommonStatus isAble, CommonStatus isCurrentTerm, LotteryTermStatus status, String result, String resultDetail,
                               String awardPool, String testMachineCode) {
		this.id = id;
		this.lotteryType = lotteryType;
		this.term = term;
		this.openDateTime = openDateTime;
		this.startDateTime = startDateTime;
		this.endDateTime = endDateTime;
		this.terminalEndDateTime = terminalEndDateTime;
		this.isAble = isAble;
		this.isCurrentTerm = isCurrentTerm;
		this.status = status;
		this.result = result;
		this.resultDetail = resultDetail;
		this.awardPool = awardPool;
		this.testMachineCode = testMachineCode;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public LotteryType getLotteryType() {
		return this.lotteryType;
	}

	public void setLotteryType(LotteryType lotteryType) {
		this.lotteryType = lotteryType;
	}

	public String getTerm() {
		return this.term;
	}

	public void setTerm(String term) {
		this.term = term;
	}

	public Date getOpenDateTime() {
		return this.openDateTime;
	}

	public void setOpenDateTime(Date openDateTime) {
		this.openDateTime = openDateTime;
	}

	public Date getStartDateTime() {
		return this.startDateTime;
	}

	public void setStartDateTime(Date startDateTime) {
		this.startDateTime = startDateTime;
	}

	public Date getEndDateTime() {
		return this.endDateTime;
	}

	public void setEndDateTime(Date endDateTime) {
		this.endDateTime = endDateTime;
	}

	public Date getTerminalEndDateTime() {
		return this.terminalEndDateTime;
	}

	public void setTerminalEndDateTime(Date terminalEndDateTime) {
		this.terminalEndDateTime = terminalEndDateTime;
	}

	public CommonStatus getIsAble() {
		return this.isAble;
	}

	public void setIsAble(CommonStatus isAble) {
		this.isAble = isAble;
	}

	public CommonStatus getIsCurrentTerm() {
		return this.isCurrentTerm;
	}

	public void setIsCurrentTerm(CommonStatus isCurrentTerm) {
		this.isCurrentTerm = isCurrentTerm;
	}

	public LotteryTermStatus getStatus() {
		return this.status;
	}

	public void setStatus(LotteryTermStatus status) {
		this.status = status;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getResultDetail() {
		return this.resultDetail;
	}

	public void setResultDetail(String resultDetail) {
		this.resultDetail = resultDetail;
	}

	public String getAwardPool() {
		return this.awardPool;
	}

	public void setAwardPool(String awardPool) {
		this.awardPool = awardPool;
	}

	public String getTotalAmount() {
		return totalAmount;
	}

	public void setTotalAmount(String totalAmount) {
		this.totalAmount = totalAmount;
	}

	public String getOutTerm() {
		return outTerm;
	}

	public void setOutTerm(String outTerm) {
		this.outTerm = outTerm;
	}

	public CommonStatus getIsBooking() {
		return isBooking;
	}

	public void setIsBooking(CommonStatus isBooking) {
		this.isBooking = isBooking;
	}

	public String getTestMachineCode() {
		return testMachineCode;
	}

	public void setTestMachineCode(String testMachineCode) {
		this.testMachineCode = testMachineCode;
	}

	public CommonStatus getLotMgrIsAble() {
		return lotMgrIsAble;
	}

	public void setLotMgrIsAble(CommonStatus lotMgrIsAble) {
		this.lotMgrIsAble = lotMgrIsAble;
	}

}