package com.qiyun.grabber;

import com.qiyun.commonModel.LotteryType;
import com.qiyun.commonModel.Platform;
import com.qiyun.commonModel.PlayType;
import com.qiyun.commonModel.TradeType;
import com.qiyun.status.ChaseStatus;
import com.qiyun.type.*;

import java.util.Date;

/**
 * AbstractLotteryChase generated by MyEclipse Persistence Tools
 */

public abstract class AbstractLotteryChase implements java.io.Serializable {

    // Fields
    // 追号编号
    private Integer chaseNo;
    // 帐号
    private String account;
    // 彩种
    private LotteryType lotteryType;
    // 类型
    private ChaseType chaseType;
    // 总金额
    private Integer amount;
    // 内容格式
    private String chaseContent;
    // 状态
    private ChaseStatus status;
    // 使用的钱包类型
    private WalletType walletType;
    // 选择类型
    private SelectType selectType;
    // 玩法
    private PlayType playType;
    // 倍数
    private Integer multiple;
    // 辅助字段 大乐透的追加
    private String addAttribute;
    // md5验证码
    private String verifyMd5;

    private Date createDateTime;

    // 2011-04-13 add by sxh
    // 是否套餐
    private PackageType isPackage;
    // 优惠后金额
    private Double packageAmount;
    // 追号总期数
    private Integer totalTerm;
    // 已追期数
    private Integer soldTerm;
    // 总奖金
    private Double totalPrize;
    // 终止条件
    private String stopCondition;
    // 开始条件
    private String startCondition;
    //盈利条件
    private String gainCondition;

    //追号标识状态
    private GenType genType;

    private Platform platform;

    private TradeType tradeType;

    // Constructors

    /**
     * default constructor
     */
    public AbstractLotteryChase() {
    }

    /**
     * full constructor
     */
    public AbstractLotteryChase(Integer chaseNo, String account, LotteryType lotteryType, ChaseType chaseType,
                                Integer amount, String chaseContent, ChaseStatus status, WalletType walletType,
                                SelectType selectType, PlayType playType, Integer multiple, String addAttribute,
                                String verifyMd5, Integer totalTerm, Integer soldTerm, GenType genType) {
        this.chaseNo = chaseNo;
        this.account = account;
        this.lotteryType = lotteryType;
        this.chaseType = chaseType;
        this.amount = amount;
        this.chaseContent = chaseContent;
        this.status = status;
        this.walletType = walletType;
        this.selectType = selectType;
        this.playType = playType;
        this.multiple = multiple;
        this.addAttribute = addAttribute;
        this.verifyMd5 = verifyMd5;
        this.totalTerm = totalTerm;
        this.soldTerm = soldTerm;
        this.genType = genType;
    }

    // Property accessors

    public Integer getChaseNo() {
        return this.chaseNo;
    }

    public void setChaseNo(Integer chaseNo) {
        this.chaseNo = chaseNo;
    }

    public String getAccount() {
        return this.account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public LotteryType getLotteryType() {
        return this.lotteryType;
    }

    public void setLotteryType(LotteryType lotteryType) {
        this.lotteryType = lotteryType;
    }

    public ChaseType getChaseType() {
        return this.chaseType;
    }

    public GenType getGenType() {
        return genType;
    }

    public void setGenType(GenType genType) {
        this.genType = genType;
    }

    public void setChaseType(ChaseType chaseType) {
        this.chaseType = chaseType;
    }

    public Integer getAmount() {
        return this.amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public String getChaseContent() {
        return this.chaseContent;
    }

    public void setChaseContent(String chaseContent) {
        this.chaseContent = chaseContent;
    }

    public ChaseStatus getStatus() {
        return this.status;
    }

    public void setStatus(ChaseStatus status) {
        this.status = status;
    }

    public WalletType getWalletType() {
        return this.walletType;
    }

    public void setWalletType(WalletType walletType) {
        this.walletType = walletType;
    }

    public SelectType getSelectType() {
        return this.selectType;
    }

    public void setSelectType(SelectType selectType) {
        this.selectType = selectType;
    }

    public PlayType getPlayType() {
        return this.playType;
    }

    public void setPlayType(PlayType playType) {
        this.playType = playType;
    }

    public Integer getMultiple() {
        return this.multiple;
    }

    public void setMultiple(Integer multiple) {
        this.multiple = multiple;
    }

    public String getAddAttribute() {
        return this.addAttribute;
    }

    public void setAddAttribute(String addAttribute) {
        this.addAttribute = addAttribute;
    }

    public String getVerifyMd5() {
        return this.verifyMd5;
    }

    public void setVerifyMd5(String verifyMd5) {
        this.verifyMd5 = verifyMd5;
    }

    public Date getCreateDateTime() {
        return createDateTime;
    }

    public void setCreateDateTime(Date createDateTime) {
        this.createDateTime = createDateTime;
    }

    public PackageType getIsPackage() {
        return isPackage;
    }

    public void setIsPackage(PackageType isPackage) {
        this.isPackage = isPackage;
    }

    public Double getPackageAmount() {
        return packageAmount;
    }

    public void setPackageAmount(Double packageAmount) {
        this.packageAmount = packageAmount;
    }

    public Integer getTotalTerm() {
        return totalTerm;
    }

    public void setTotalTerm(Integer totalTerm) {
        this.totalTerm = totalTerm;
    }

    public Integer getSoldTerm() {
        return soldTerm;
    }

    public void setSoldTerm(Integer soldTerm) {
        this.soldTerm = soldTerm;
    }

    public Double getTotalPrize() {
        return totalPrize;
    }

    public void setTotalPrize(Double totalPrize) {
        this.totalPrize = totalPrize;
    }

    public String getStopCondition() {
        return stopCondition;
    }

    public void setStopCondition(String stopCondition) {
        this.stopCondition = stopCondition;
    }

    public String getStartCondition() {
        return startCondition;
    }

    public void setStartCondition(String startCondition) {
        this.startCondition = startCondition;
    }

    public Platform getPlatform() {
        return platform;
    }

    public void setPlatform(Platform platform) {
        this.platform = platform;
    }

    public String getGainCondition() {
        return gainCondition;
    }

    public void setGainCondition(String gainCondition) {
        this.gainCondition = gainCondition;
    }

    public TradeType getTradeType() {
        return tradeType;
    }

    public void setTradeType(TradeType tradeType) {
        this.tradeType = tradeType;
    }


}