package com.qiyun.grabber.model;

import com.qiyun.commonModel.LotteryType;
import com.qiyun.model.MemberOperType;
import com.qiyun.model.Platform;

import java.util.Date;

/**
 * AbstractMemberOperTrack generated by MyEclipse Persistence Tools
 */

public abstract class AbstractMemberOperTrack implements java.io.Serializable {

	// Fields
	// 操作流水编号
	private Long id;
	// 设备id
	private String terminalId;
	// 会员帐号
	private String account;
	//平台
	private Platform platform;
	//版本
	private String version;	
	// 操作类型
	private MemberOperType operType;
	//模块
	private String module;
	private String module1;
	private String module2;
	//彩种
	private LotteryType lotteryType;
	//浏览器
	private String browser;
	//操作系统
	private String os;
	//外包流水ID
	private Long externalId;
	// ip地址
	private String ip;
	// ip所解析的地区
	private String fromCountry;
	private String fromArea;
	// 生成时间
	private Date createDateTime;
	
	private String rev1;
	private String rev2;

	/** default constructor */
	public AbstractMemberOperTrack() {
	}

	public AbstractMemberOperTrack(MemberOperType memberOperType,Platform platform,String account,LotteryType lotteryType,String terminalId){
		this.account = account;
		this.operType = memberOperType;
		this.platform = platform;
		this.lotteryType = lotteryType;
		this.terminalId = terminalId;
		this.createDateTime = new Date();
	}
	// Property accessors

	public String getTerminalId() {
		return this.terminalId;
	}

	public void setTerminalId(String terminalId) {
		this.terminalId = terminalId;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public MemberOperType getOperType() {
		return this.operType;
	}

	public void setOperType(MemberOperType operType) {
		this.operType = operType;
	}

	public Date getCreateDateTime() {
		return this.createDateTime;
	}

	public void setCreateDateTime(Date createDateTime) {
		this.createDateTime = createDateTime;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Platform getPlatform() {
		return platform;
	}

	public void setPlatform(Platform platform) {
		this.platform = platform;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getModule() {
		return module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public String getModule1() {
		return module1;
	}

	public void setModule1(String module1) {
		this.module1 = module1;
	}

	public String getModule2() {
		return module2;
	}

	public void setModule2(String module2) {
		this.module2 = module2;
	}

	public LotteryType getLotteryType() {
		return lotteryType;
	}

	public void setLotteryType(LotteryType lotteryType) {
		this.lotteryType = lotteryType;
	}

	public String getBrowser() {
		return browser;
	}

	public void setBrowser(String browser) {
		this.browser = browser;
	}

	public String getOs() {
		return os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	public Long getExternalId() {
		return externalId;
	}

	public void setExternalId(Long externalId) {
		this.externalId = externalId;
	}

	public String getFromCountry() {
		return fromCountry;
	}

	public void setFromCountry(String fromCountry) {
		this.fromCountry = fromCountry;
	}

	public String getFromArea() {
		return fromArea;
	}

	public void setFromArea(String fromArea) {
		this.fromArea = fromArea;
	}

	public String getRev1() {
		return rev1;
	}

	public void setRev1(String rev1) {
		this.rev1 = rev1;
	}

	public String getRev2() {
		return rev2;
	}

	public void setRev2(String rev2) {
		this.rev2 = rev2;
	}
}