package com.qiyun.grabber.model;


import com.qiyun.commonModel.LotteryType;
import com.qiyun.status.CommonStatus;

/**
 * AbstractLotteryTypeProps generated by MyEclipse Persistence Tools
 */
public abstract class AbstractLotteryTypeProps implements java.io.Serializable {

	// Fields
	// 彩种
	private Integer lotteryType;
	// 每包数量
	private Integer countInBatch;
	// 打包等待时间
	private Integer maxWaitTime;
	// 单式提前截止时间
	private Integer dsAheadTime;
	// 复式提前截止时间
	private Integer fsAheadTime;
	
	private Long price;//人气
	private Double discount;//奖金
	private Long total;//销售
	private String describe;//描述
	private Long isHotSales;//是否热销
	private String presentation;//提示
	private Long promotion;//提示促销标签
	private Long defaultSort;//默认排序
	private String onImp;//开售图标
	private String stopImp;//停售图标
	private String buyLink;//购买链接
	private String lotteryGuideImg;//彩种提示图标
	private String stopCause;//停售原因
	private String cmdLottery;//推荐彩种;
	private CommonStatus lotMgrIsAble;//彩期管家是否开售
	

	// Constructors

	/** default constructor */
	public AbstractLotteryTypeProps() {
	}

	/** full constructor */
	public AbstractLotteryTypeProps(Integer lotteryType, Integer countInBatch, Integer maxWaitTime, Integer dsAheadTime, Integer fsAheadTime) {
		this.lotteryType = lotteryType;
		this.countInBatch = countInBatch;
		this.maxWaitTime = maxWaitTime;
		this.dsAheadTime = dsAheadTime;
		this.fsAheadTime = fsAheadTime;
	}

	// Property accessors

	public Integer getLotteryType() {
		return this.lotteryType;
	}

	public void setLotteryType(Integer lotteryType) {
		this.lotteryType = lotteryType;
	}

	public Integer getCountInBatch() {
		return this.countInBatch;
	}

	public void setCountInBatch(Integer countInBatch) {
		this.countInBatch = countInBatch;
	}

	public Integer getMaxWaitTime() {
		return this.maxWaitTime;
	}

	public void setMaxWaitTime(Integer maxWaitTime) {
		this.maxWaitTime = maxWaitTime;
	}

	public Integer getDsAheadTime() {
		return this.dsAheadTime;
	}

	public void setDsAheadTime(Integer dsAheadTime) {
		this.dsAheadTime = dsAheadTime;
	}

	public Integer getFsAheadTime() {
		return this.fsAheadTime;
	}

	public void setFsAheadTime(Integer fsAheadTime) {
		this.fsAheadTime = fsAheadTime;
	}

	public Long getPrice() {
		return price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	public Double getDiscount() {
		return discount;
	}

	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	public Long getTotal() {
		return total;
	}

	public void setTotal(Long total) {
		this.total = total;
	}

	public String getDescribe() {
		return describe;
	}

	public void setDescribe(String describe) {
		this.describe = describe;
	}

	public Long getIsHotSales() {
		return isHotSales;
	}

	public void setIsHotSales(Long isHotSales) {
		this.isHotSales = isHotSales;
	}

	public String getPresentation() {
		return presentation;
	}

	public void setPresentation(String presentation) {
		this.presentation = presentation;
	}

	public Long getPromotion() {
		return promotion;
	}

	public void setPromotion(Long promotion) {
		this.promotion = promotion;
	}

	public Long getDefaultSort() {
		return defaultSort;
	}

	public void setDefaultSort(Long defaultSort) {
		this.defaultSort = defaultSort;
	}

	public String getOnImp() {
		return onImp;
	}

	public void setOnImp(String onImp) {
		this.onImp = onImp;
	}

	public String getStopImp() {
		return stopImp;
	}

	public void setStopImp(String stopImp) {
		this.stopImp = stopImp;
	}

	public String getBuyLink() {
		return buyLink;
	}

	public void setBuyLink(String buyLink) {
		this.buyLink = buyLink;
	}

	public String getLotteryGuideImg() {
		return lotteryGuideImg;
	}

	public void setLotteryGuideImg(String lotteryGuideImg) {
		this.lotteryGuideImg = lotteryGuideImg;
	}

	public LotteryType getToLotteryType() {
		return LotteryType.getItem(lotteryType);
	}

	public String getStopCause() {
		return stopCause;
	}

	public void setStopCause(String stopCause) {
		this.stopCause = stopCause;
	}

	public String getCmdLottery() {
		return cmdLottery;
	}

	public void setCmdLottery(String cmdLottery) {
		this.cmdLottery = cmdLottery;
	}

	public CommonStatus getLotMgrIsAble() {
		return lotMgrIsAble;
	}

	public void setLotMgrIsAble(CommonStatus lotMgrIsAble) {
		this.lotMgrIsAble = lotMgrIsAble;
	}

}