package com.qiyun.grabber.model;

/**
 * AbstractFootballTeam generated by MyEclipse Persistence Tools
 */

public abstract class AbstractFootballTeam implements java.io.Serializable {

	// Fields

	private Integer id;

	private String standardName;

	private String dc;

	private String jc;

	private String fb;

	private String dyj;
	
	private Integer pm;

	// Constructors

	/** default constructor */
	public AbstractFootballTeam() {
	}

	/** full constructor */
	public AbstractFootballTeam(String dc, String jc, String fb, String dyj) {
		this.dc = dc;
		this.jc = jc;
		this.fb = fb;
		this.dyj = dyj;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDc() {
		return this.dc;
	}

	public void setDc(String dc) {
		this.dc = dc;
	}

	public String getJc() {
		return this.jc;
	}

	public void setJc(String jc) {
		this.jc = jc;
	}

	public String getFb() {
		return this.fb;
	}

	public void setFb(String fb) {
		this.fb = fb;
	}

	public String getDyj() {
		return this.dyj;
	}

	public void setDyj(String dyj) {
		this.dyj = dyj;
	}

	public String getStandardName() {
		return standardName;
	}

	public void setStandardName(String standardName) {
		this.standardName = standardName;
	}

	public Integer getPm() {
		return pm;
	}

	public void setPm(Integer pm) {
		this.pm = pm;
	}

}