package com.qiyun.grabber.model;

import com.qiyun.util.NumberTools;

import java.util.Date;


/**
 * AbstractFootballMatch generated by MyEclipse Persistence Tools
 */

public abstract class AbstractMatchBase implements java.io.Serializable {

	// Fields

	private Integer id;

	/** 赛事名称时间 * */
	private String matchName;
	/** 主队名称 * */
	private String home;
	/** 主队ID * */
	private Integer homeId;
	/** 客队名称 * */
	private String guest;
	/** 客队ID * */
	private Integer guestId;
	/** 比赛时间 * */
	private Date matchTime;

	private String matchDateStr; //


	private String bfWhole; // 全场

	private String analysisId; // 分析ID

	private String oddId; // 指数
	/** 联赛关联ID * */
	private Integer gameId;
	
	// 主队最终进球数
	private Integer finalHomeScore;
	// 客队最终进球数
	private Integer finalGuestScore;
	// Constructors

	private String homePm; // 主队排名

	private String guestPm; // 客队排名
	
	private Integer intTime;
	
	private Integer lineId;
	
	private String mapKey;//用这个关联对阵表


	/** default constructor */
	public AbstractMatchBase() {
	}

	/** full constructor */
	public AbstractMatchBase(Integer id, String home, Integer homeId, String guest, Integer guestId, Date matchTime, String matchDateStr,
			String bfWhole, String analysisId, String oddId, Integer gameId, String homePm, String guestPm, Integer finalHomeScore,
			Integer finalGuestScore) {
		this.id = id;
		this.home = home;
		this.homeId = homeId;
		this.guest = guest;
		this.guestId = guestId;
		this.matchTime = matchTime;
		this.matchDateStr = matchDateStr;
		this.bfWhole = bfWhole;
		this.analysisId = analysisId;
		this.oddId = oddId;
		this.gameId = gameId;
		this.homePm = homePm;
		this.guestPm = guestPm;
		this.finalGuestScore=finalGuestScore;
		this.finalHomeScore=finalHomeScore;

	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getHome() {
		return this.home;
	}

	public void setHome(String home) {
		this.home = home;
	}

	public Integer getHomeId() {
		return this.homeId;
	}

	public void setHomeId(Integer homeId) {
		this.homeId = homeId;
	}

	public String getGuest() {
		return this.guest;
	}

	public void setGuest(String guest) {
		this.guest = guest;
	}

	public Integer getGuestId() {
		return this.guestId;
	}

	public void setGuestId(Integer guestId) {
		this.guestId = guestId;
	}

	public Date getMatchTime() {
		return this.matchTime;
	}

	public void setMatchTime(Date matchTime) {
		this.matchTime = matchTime;
	}

	public String getMatchDateStr() {
		return this.matchDateStr;
	}

	public void setMatchDateStr(String matchDateStr) {
		this.matchDateStr = matchDateStr;
	}

	public String getBfWhole() {
		return this.bfWhole;
	}

	public void setBfWhole(String bfWhole) {
		this.bfWhole = bfWhole;
		if (!"".equals(this.bfWhole) && this.bfWhole != null) {
			String[] tempArr = bfWhole.split(":");
			if (NumberTools.isNum(tempArr[0]) && NumberTools.isNum(tempArr[1])) {
				Integer homeScore = Integer.valueOf(tempArr[0]);
				Integer guestScore = Integer.valueOf(tempArr[1]);
				this.setFinalHomeScore(homeScore);
				this.setFinalGuestScore(guestScore);
			}
		}
	}

	public String getAnalysisId() {
		return this.analysisId;
	}

	public void setAnalysisId(String analysisId) {
		this.analysisId = analysisId;
	}

	public String getOddId() {
		return this.oddId;
	}

	public void setOddId(String oddId) {
		this.oddId = oddId;
	}

	public String getMatchName() {
		return matchName;
	}

	public void setMatchName(String matchName) {
		this.matchName = matchName;
	}

	public Integer getGameId() {
		return gameId;
	}

	public void setGameId(Integer gameId) {
		this.gameId = gameId;
	}

	public String getHomePm() {
		return homePm;
	}

	public void setHomePm(String homePm) {
		this.homePm = homePm;
	}

	public String getGuestPm() {
		return guestPm;
	}

	public void setGuestPm(String guestPm) {
		this.guestPm = guestPm;
	}

	public static void main(String[] args) {
	}

	public Integer getFinalHomeScore() {
		return finalHomeScore;
	}

	public void setFinalHomeScore(Integer finalHomeScore) {
		this.finalHomeScore = finalHomeScore;
	}

	public Integer getFinalGuestScore() {
		return finalGuestScore;
	}

	public void setFinalGuestScore(Integer finalGuestScore) {
		this.finalGuestScore = finalGuestScore;
	}

	public Integer getIntTime() {
		return intTime;
	}

	public void setIntTime(Integer intTime) {
		this.intTime = intTime;
	}

	public Integer getLineId() {
		return lineId;
	}

	public void setLineId(Integer lineId) {
		this.lineId = lineId;
	}

}