package com.qiyun.model;

// Generated by MyEclipse Persistence Tools

import com.qiyun.commonModel.LotteryType;
import com.qiyun.grabber.AbstractLotteryChaseTerm;
import com.qiyun.status.ChaseTermStatus;

/**
 * LotteryChaseTerm generated by MyEclipse Persistence Tools
 */
public class LotteryChaseTerm extends AbstractLotteryChaseTerm implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public LotteryChaseTerm() {
	}

	/** minimal constructor */
	public LotteryChaseTerm(Integer chaseNo, LotteryType lotteryType, String term, ChaseTermStatus status, Integer multiple, Integer amount) {
		super(chaseNo, lotteryType, term, status, multiple, amount);
	}

	/** full constructor */
	public LotteryChaseTerm(Integer chaseNo, LotteryType lotteryType, String term, ChaseTermStatus status, Integer multiple, Integer amount,
			Integer planNo) {
		super(chaseNo, lotteryType, term, status, multiple, amount, planNo);
	}

}
