package com.qiyun.model;

// Generated by MyEclipse Persistence Tools

import com.qiyun.tools.StringTools;

import java.util.Date;

/**
 * Member generated by MyEclipse Persistence Tools
 */
public class Member extends AbstractMember implements java.io.Serializable {

	// Constructors
	private static final long serialVersionUID = 1L;
	private MemberWallet wallet;
	


	/** default constructor */
	public Member() {
	}

	/** minimal constructor */
	public Member(String account, String name, Integer certType, String certNo, String password, Integer rank, String email, String mobile,
			Integer status, Integer exprerience, Integer sourceId) {
		super(account, name, certType, certNo, password, rank, email, mobile, status, exprerience, sourceId);
	}

	/** full constructor */
	public Member(String account, String name, Integer certType, String certNo, String password, Integer rank, String email, String mobile,
			Integer status, Date registerDateTime, Date lastLoginDateTime, Integer exprerience, Integer sourceId, Integer recommender) {
		super(account, name, certType, certNo, password, rank, email, mobile, status, registerDateTime, lastLoginDateTime, exprerience, sourceId,
				recommender);
	}

	public MemberWallet getWallet() {
		return wallet;
	}

	public void setWallet(MemberWallet wallet) {
		this.wallet = wallet;
	}

	public String getNameSec() {
		String src = this.getName();
		if(src == null ) return "";
		return StringTools.getSecStr(src, 1, src.length());

	}

	public String getCertNoSec() {
		String src = this.getCertNo();
		if(src == null ) return "";
		return StringTools.getSecStr(src, 4, src.length() - 3);

	}
	
	public String getMobileSec() {
		String src = this.getMobile();
		if(src == null ) return "";
		return StringTools.getSecStr(src, 3, src.length() - 3);

	}
	
	public String getEmailSec(){
		String src = this.getEmail();
		if(src == null ) return "";
		String tem = this.getEmail().split("@")[1];
		String tem2 = "@" + tem;
		return  StringTools.getSecStr(src, 3, src.length() - tem2.length());
	}

	/**
	 * 返回用户头相地址
	 */
	public String getPictureUrl(){
		if (!StringTools.isNullOrBlank(getPicture())) {
				return "/upload/HeadPicture/"+this.getPicture();
		} 
		return DomainConfig.getStatic()+ "/upload/HeadPicture/avatar1.png";
	}
}
