package com.qiyun.chaiPiao;

import java.util.Date;

/**
 * AbstractFootballDxp generated by MyEclipse Persistence Tools
 */

public abstract class AbstractBasketballDxp implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer matchId;
	
	private String company;
	
	private Double big;

	private Integer bigChange=0;

	private Double pankou;

	private Integer pankouChange=0;

	private Double small;

	private Integer smallChange=0;

	private Integer isFirst;

	private Date time;

	// Constructors

	/** default constructor */
	public AbstractBasketballDxp() {
	}

	/** minimal constructor */
	public AbstractBasketballDxp(Integer matchId) {
		this.matchId = matchId;
	}

	/** full constructor */
	public AbstractBasketballDxp(Integer matchId, Double big, Integer bigChange, Double pankou, Integer pankouChange, Double small,
			Integer smallChange, Integer isFirst, Date time) {
		this.matchId = matchId;
		this.big = big;
		this.bigChange = bigChange;
		this.pankou = pankou;
		this.pankouChange = pankouChange;
		this.small = small;
		this.smallChange = smallChange;
		this.isFirst = isFirst;
		this.time = time;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getMatchId() {
		return this.matchId;
	}

	public void setMatchId(Integer matchId) {
		this.matchId = matchId;
	}

	public Double getBig() {
		return this.big;
	}

	public void setBig(Double big) {
		this.big = big;
	}

	public Integer getBigChange() {
		return this.bigChange;
	}

	public void setBigChange(Integer bigChange) {
		this.bigChange = bigChange;
	}

	public Double getPankou() {
		return this.pankou;
	}

	public void setPankou(Double pankou) {
		this.pankou = pankou;
	}

	public Integer getPankouChange() {
		return this.pankouChange;
	}

	public void setPankouChange(Integer pankouChange) {
		this.pankouChange = pankouChange;
	}

	public Double getSmall() {
		return this.small;
	}

	public void setSmall(Double small) {
		this.small = small;
	}

	public Integer getSmallChange() {
		return this.smallChange;
	}

	public void setSmallChange(Integer smallChange) {
		this.smallChange = smallChange;
	}

	public Integer getIsFirst() {
		return this.isFirst;
	}

	public void setIsFirst(Integer isFirst) {
		this.isFirst = isFirst;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

}