package com.qiyun.model;

public class MemberScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_score.member_id
     *
     * @mbg.generated
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_score.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_score.usable_score
     *
     * @mbg.generated
     */
    private Integer usableScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_score.history_score
     *
     * @mbg.generated
     */
    private Integer historyScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_score.member_id
     *
     * @return the value of member_score.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_score.member_id
     *
     * @param memberId the value for member_score.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_score.account
     *
     * @return the value of member_score.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_score.account
     *
     * @param account the value for member_score.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_score.usable_score
     *
     * @return the value of member_score.usable_score
     *
     * @mbg.generated
     */
    public Integer getUsableScore() {
        return usableScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_score.usable_score
     *
     * @param usableScore the value for member_score.usable_score
     *
     * @mbg.generated
     */
    public void setUsableScore(Integer usableScore) {
        this.usableScore = usableScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_score.history_score
     *
     * @return the value of member_score.history_score
     *
     * @mbg.generated
     */
    public Integer getHistoryScore() {
        return historyScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_score.history_score
     *
     * @param historyScore the value for member_score.history_score
     *
     * @mbg.generated
     */
    public void setHistoryScore(Integer historyScore) {
        this.historyScore = historyScore;
    }
}